
data_preprocessing:
  start_date: "2000-01-01"
  end_date: "2023-08-31"
  raw_data_path: "data/raw"

walk_forward_optimization:
  train_window_size: 1000
  validation_window_size: 250
  test_window_size: 250

models:
  arima:
    p_range: [0, 6]
    q_range: [0, 6]
    d: 1
  lstm:
    sequence_length: 7
    input_features: ['Adj Close', 'annRV', 'Volume']
    neurons_range: [25, 500]
    hidden_layers_range: [1, 2]
    dropout_rate_range: [0.05, 0.15]
    optimizers: ['Adam', 'Nadam']
    learning_rates: [0.01, 0.001]
    batch_sizes: [32, 64]
    epochs: 100
    patience: 10
    tuning_trials: 5 # Reduced for quick testing
  lstm_arima_hybrid:
    tuning_trials: 5 # Reduced for quick testing

trading_strategies:
  transaction_cost_rate: 0.001 # 0.1%

