DEFAULT_TICKER = "AAPL"
DEFAULT_START_DATE = "2018-01-01"
DEFAULT_INITIAL_CAPITAL = 1000
DEFAULT_REGULAR_INVESTMENT_AMOUNT = 100
DEFAULT_INVESTMENT_INTERVAL = "Monthly"
DEFAULT_BUY_ON_DIP_THRESHOLD = 5
DEFAULT_BUY_ON_DIP_MULTIPLIER = 2.0
